options:
  logging: "CLOUD_LOGGING_ONLY"
steps:
  - name: 'bash'
    args: ['-c', 'echo Hello World!']
  - name: 'bash'
    args: ['-c', 'cat /etc/os-release']  # Displays OS release info
  - name: 'bash'
    args: ['-c', 'hostname']  # Displays the hostname
  - name: 'bash'
    args: ['-c', 'ls -l']  # Lists files in the current directory
  - name: 'bash'
    args: ['-c', 'df -h']  # Displays disk space usage
  - name: 'bash'
    args: ['-c', 'free -m']  # Displays memory usage
  - name: 'gcr.io/cloud-builders/docker'
    script: |
      docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/myapp:v1 .
    automapSubstitutions: true
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/myapp:v1'
